export const SET_STATE = 'SET_STATE';
export const CHANGE_CURRENCY_AMOUNT = 'CHANGE_CURRENCY_AMOUNT';
export const CHANGE_CURRENCY_INVEST_RATE = 'CHANGE_CURRENCY_INVEST_RATE';
export const CHANGE_CURRENCY_EXCHANGE_RATE = 'CHANGE_CURRENCY_EXCHANGE_RATE';
export const CHANGE_USER_CURRENCY = 'CHANGE_USER_CURRENCY';
export const CHANGE_USE_INVEST = 'CHANGE_USE_INVEST';
export const ADD_CURRENCY = 'ADD_CURRENCY';

export const CHANGE_CIRCLE_COORD = 'CHANGE_CIRCLE_COORD';
export const START_EXCHANGE_RATE_CHANGING = 'START_EXCHANGE_RATE_CHANGING';
export const STOP_EXCHANGE_RATE_CHANGING = 'STOP_EXCHANGE_RATE_CHANGING';
